//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DislayOrder { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
